version: 3

silent: true

vars:
  GINZA_DIR: ginza_http_api
  PYMAGNITUDE_DIR: pymagnitude_http_api

tasks:
  submodule:update:
    cmds:
      - git submodule update --remote
  line:dev:
    cmds:
      - yarn ts ./src/index.ts
  line:run:
    cmds:
      - yarn install
      - yarn pm2 start ./dist/index.js
  line:kill:
    cmds:
      - yarn pm2 stop ./dist/index.js
  ginza:run:
    dir: "{{.GINZA_DIR}}"
    cmds:
      - poetry install
      - poetry run task run_prod
  ginza:kill:
    dir: "{{.GINZA_DIR}}"
    cmds:
      - poetry run task kill_prod
  pymagnitude:run:
    dir: "{{.PYMAGNITUDE_DIR}}"
    cmds:
      - docker compose up -d
  pymagnitude:kill:
    dir: "{{.PYMAGNITUDE_DIR}}"
    cmds:
      - docker compose down
