version: 3

silent: true

vars:
  GINZA_DIR: ginza_http_api

tasks:
  ginza:setup:
    dir: "{{.GINZA_DIR}}"
    cmds:
      - poetry install
  ginza:dev:
    dir: "{{.GINZA_DIR}}"
    cmds:
      - poetry run task run_dev
  ginza:run:
    dir: "{{.GINZA_DIR}}"
    cmds:
      - poetry run task run_prod
  ginza:kill:
    dir: "{{.GINZA_DIR}}"
    cmds:
      - poetry run task kill_prod
