version: 3

silent: true

vars:
  GINZA_DIR: ginza_http_api
  PYMAGNITUDE_DIR: pymagnitude_http_api

tasks:
  submodule:update:
    cmds:
      - git submodule update --remote

  line:expose:
    cmds:
      - yarn lt --port 45300 --subdomain ${LT_SUBDOMAIN}
  line:dev:
    cmds:
      - yarn ts ./src/index.ts
  line:run:
    cmds:
      - yarn install
      - yarn pm2 start ./dist/index.js
  line:kill:
    cmds:
      - yarn pm2 stop ./dist/index.js

  ginza:dev:
    dir: "{{.GINZA_DIR}}"
    cmds:
      - poetry run uvicorn main:app --reload --port 45100
  ginza:run:
    dir: "{{.GINZA_DIR}}"
    cmds:
      - poetry install
      - poetry run gunicorn -c gunicorn.conf.py main:app
  ginza:kill:
    dir: "{{.GINZA_DIR}}"
    cmds:
      - kill `cat prod.pid`
      
  pymagnitude:run:
    dir: "{{.PYMAGNITUDE_DIR}}"
    cmds:
      - docker compose up -d
  pymagnitude:kill:
    dir: "{{.PYMAGNITUDE_DIR}}"
    cmds:
      - docker compose down
